name: Deploy static content to Pages

on:
  push:
    branches: [master]  # 推荐在代码推送时触发
  # 可选定时触发（按需启用）
  # schedule:
  #   - cron: '0 * * * *'  # 每小时运行一次

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files in docs directory
        run: ls -la ./docs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: './docs/**'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
